#  Copyright (c) VKU.NewEnergy.

#  This source code is licensed under the Apache-2.0 license found in the
#  LICENSE file in the root directory of this source tree.

_type: prompt
input_variables:
  - chat_history
  - question
template: >
  Summarize the following conversation and the user's new question into a single standalone question.
  ---

  Conversation: 

  "{chat_history}"

  ---

  New question from user: 

  "{question}"

  ---

  A standalone question:
