#  Copyright (c) VKU.NewEnergy.

#  This source code is licensed under the Apache-2.0 license found in the
#  LICENSE file in the root directory of this source tree.

qaPrompt:
  filepath: "configs/prompts/qa_prompt.yaml"
  createdDate: "2023/12/03"
condensePrompt:
  filepath: "configs/prompts/condense_prompt.yaml"
  createdDate: "2023/12/03"
summarizePrompt:
  filepath: "configs/prompts/summarize_prompt.yaml"
  createdDate: "2023/12/03"
detectLanguagePrompt:
  filepath: "configs/prompts/detect_language_prompt.yaml"
  createdDate: "2023/12/03"
